[default]
port = 1926
openapi_url = "https://example.org/api/v1/"
serve_static_directory = false
static_directory_path = "/usr/share/openkeg/swagger"
static_directory_url = "/swagger"

[default.ldap]
server = "ldap://localhost:2389"
dn = "uid=koal,ou=Musik,ou=Mitglieder,dc=mvl,dc=at"
member_base = "ou=Mitglieder,dc=mvl,dc=at"
member_filter = "(objectClass=mvlMember)"
sutler_base = "ou=Marketenderinnen,ou=Mitglieder,dc=mvl,dc=at"
sutler_filter = "(objectClass=mvlMember)"
honorary_base = "ou=Ehrenmitglieder,ou=Mitglieder,dc=mvl,dc=at"
honorary_filter = "(objectClass=mvlMember)"
register_base = "ou=Register,ou=Divisionen,dc=mvl,dc=at"
register_filter = "(objectClass=mvlGroup)"
executives_base = "ou=Exekutive,ou=Divisionen,dc=mvl,dc=at"
executives_filter = "(objectClass=mvlGroup)"
password = "Ibimsdastaschasserkoal"

[default.database]
url = "http://127.0.0.1:5984"
username = "admin"
password = "admin"
score_partition = "scores"

[default.database.database_mapping]
authentication = "/_session"
all_scores = "/archive/_partition/scores/_all_docs"
find_scores = "/archive/_partition/scores/_find"
get_score = "/archive"
put_score = "/archive"
delete_score = "/archive"
genres_statistic = "/archive/_design/score/_view/genres-count"
composers_statistic = "/archive/_design/score/_view/composers-count"
arrangers_statistic = "/archive/_design/score/_view/arrangers-count"
publishers_statistic = "/archive/_design/score/_view/publishers-count"
books_statistic = "/archive/_design/score/_view/books-count"
locations_statistic = "/archive/_design/score/_view/locations-count"

[default.ldap.executive_mapping]
archive = "Archivare"

[default.document_server.mapping]
blackboard = "blackboard"
blackboard_assets = "blackboard/Bilder"

[default.calendar]
ical_url = "https://example.org/events.ics"
ical_internal_url = "https://example.org/internal.ics"
