= OpenKeg: The Lightweight Backend of the Musikverein Leopoldsdorf
Richard Stöckl <richard.stoeckl@aon.at>

:icons: font
:source-highlighter: coderay

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

This backend especially written for the Musikverein Leopoldsdorf, provides the functionality to authenticate against a directory server, provides a REST access to them and provide a REST interface to the archive.

== Build

The project can be built with

[source,shell script]
----
cargo build --release
----

== Setup

After build some setup if required such as the configuration.

=== RSA Keys

Keg uses RSA keys for signing JWTs in the PEM format.
The following commands will generate a private key, a public key and an X.509 certificate which is valid for one year.

.Generate the keys and the certificate
[source,shell script]
----
openssl req -x509 -newkey rsa:4096 -days 365 -utf8 -nodes -outform PEM -keyform PEM -keyout keg-private-key.pem -out keg.crt -sha512
openssl rsa -in keg-private-key.pem -inform PEM -outform PEM -out keg-private-key.pem
----

== Configuration

You may copy the example configuration and change the parameters as required.
Note that the configuration contains sensitive data such as the passwords to the directory or the database servers.
This means that you should change the permissions to the configuration file such that only the user who runs application can read it.

As an alternative you might want to only omit these sensitive attributes and provide them as environment variables as described in the https://rocket.rs/v0.5-rc/guide/configuration/[Rocket Configuration Section].
The difference is that in this application, the prefix is `KEG_` instead of `ROCKET_`.
This is especially useful for container environments as in kubernetes or docker.

NOTE: Due to unknown reasons it is currently not possible to override the default config file location.

.The example configuration
[source,toml]
----
include::keg.example.toml[]
----

== Development

In order to use the pre-commit hook for formatting the code before every commit, just run `make` in the project root once.

=== Informal Coding Rules

Some rules cannot be expressed via the `.editorconfig` as they are often semantic and subject of taste.

==== Syntactic Rules

* Begin log messages uppercase

==== Coding Style Rules

* Prefer functional way over imperative

== OpenAPI

This application hosts its own OpenAPI specification in order to document the rest interface.
However, this does not include any frontends such as link:https://swagger.io/[Swagger] or link:https://rapidocweb.com/[RapiDoc].
This leads it up to the user whatever they want to use.
The schema definition is located at `/api/v1/openapi.json`.

The application provides the possibility to serve a self-contained frontend for OpenAPI.
In order to use it, one has to set `serve_static_directory = true` in the configuration and set the appropriate `static_directory_path` and `static_directory_url`.

WARNING: It is your responsibility to provide the files for the frontend and configure it properly. For this reason, it is disabled by default.

== Name Origin

As in many music societies, the consumption of kegs is common in the Musikverein Leopoldsdorf.
This makes them mandatory to be open -- a prefix which is also used for many open source projects.